version: "3.4"
services:
  tracing-example:
    image: tracing-example
    ports:
      - 8000:8000
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  tempo:
    image: grafana/tempo:0.5.0
    command: ["--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false"]
    ports:
    - 8081:80
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  tempo-query:
    image: grafana/tempo-query:latest
    environment:
    - BACKEND=tempo:80
    volumes:
    - ./etc/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
    - "16686:16686"  # jaeger-ui
    depends_on:
    - tempo
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  grafana:
    image: grafana/grafana:7.3.x-exemplars
    volumes:
    - ./config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
    - "3000:3000"

  loki:
    image: grafana/loki:2.1.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
    - "3100:3100"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  prometheus:
    image: cstyan/prometheus:exemplars-64206a
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - "9090:9090"
